name: "Stale Issue & PR Workflow"

on:
  schedule:
    - cron: "0 0 * * *" #timer - Runs at 00:00
    
  workflow_dispatch:

jobs:
  stale:
    name: Mark & Close Stale Issues & PRs
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Run Stale Action
        uses: actions/stale@v9
        
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Days of inactivity before a warning is posted
          days-before-stale: 14

          # Disable auto-closing issues
          days-before-issue-close: -1

          # Close stale PRs after 7 days
          days-before-pr-close: 7

          stale-issue-label: "stale" # Labels applied when stale
          stale-pr-label: "stale"

          # Remove stale label automatically if activity resumes
          remove-stale-when-updated: true

          # Unassign inactive users when marked stale
          remove-issue-assignees-when-stale: true

          # Comment posted for a stale issue
          stale-issue-message: >
            This issue has had no activity for **14 days**. You have been unassigned 
            so other contributors can pick it up. If you are still working on this, 
            please leave a comment to claim it again !
            Thank you for contributing to AegisGraph-Sentinel-2.0!

          # Comment posted for a stale PR
          
          stale-pr-message: >
            This pull request has had no activity for **14 days** and
            has been marked as `stale`. If you are still working on it,
            please push a commit or leave a comment within the next **7 days**,
            otherwise it will be closed automatically.
            Thank you for contributing to AegisGraph-Sentinel-2.0!


          # Comment posted for a closed stale PR 
          
          close-pr-message: >
            This pull request has been automatically closed after 21 days
            of inactivity. Please reopen or raise a new PR rebased on the
            latest master branch if you would like to continue. 
            Thank you for contributing to AegisGraph-Sentinel-2.0!

          # Issues and PRs with these labels are never touched by the sweeper
          
          exempt-issue-labels: "pinned,security,critical,in-progress,blocked,help wanted,gssoc:approved"
          
          exempt-pr-labels: "pinned,security,critical,in-progress,blocked,do-not-merge,gssoc:approved"

          # Cap API calls per run to respect GitHub rate limits
          operations-per-run: 75

          # Process oldest items first
          ascending: true  
